version: '2'
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=test
        - LDAP_DOMAIN=test.com
        - "LDAP_BASE_DN=dc=test,dc=com"
        - LDAP_ADMIN_PASSWORD=test
    ports:
        - 389:389
        - 636:636